os:
  - windows
  - linux
  - osx
language: rust
rust:
  - nightly
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then chmod +x install_linux.sh && ./install_linux.sh; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then chmod +x install_osx.sh && ./install_osx.sh; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then ./install_win.bat; fi
  - cargo install --force cargo-make
script:
  - cargo make --makefile Makefile.toml build-all
addons:
  homebrew:
    update: true
    packages:
    - node
    - yarn
  apt:
    update: true