os:
  - windows
  - linux
  - osx
language: rust
rust:
  - nightly
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then ./install_linux.sh; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then ./install_osx.sh; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then install_win.bat; fi
  - cargo install --force cargo-make
script:
  - cargo make --makefile Makefile.toml build-all