os:
  - windows
  - linux
  - osx
language: rust
rust:
  - nightly
script:
  - cargo install --force cargo-make
  - cargo make --makefile Makefile.toml build-all
before_install:
  - echo before install
  - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo someelse; fi