os:
  - windows
  - linux
  - osx
language: rust
rust:
  - nightly
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then echo osx; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then echo windows; fi
  - cargo install --force cargo-make
script:
  - cargo make --makefile Makefile.toml build-all