[tasks.build-gui]
cwd = "packages/open-cleaner"
install_script = [
    "yarn"
]
script = [
    "yarn build"
]

[tasks.build-all]
dependencies = ["build-gui"]
script = [
    "echo hello"
]